# DEVELOPMENT COMPOSE FILE - FOR PRODOCTION IN SWARM USE THE ONE IN FOLDER "production"
# Define .env file as in .env.example 
version: "3.9"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      #db creation only first run (if volumes attached)
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASS_DB}
      MYSQL_DATABASE: ${DB_NAME}
    volumes: 
      - mysql-data:/var/lib/mysql

  app:
    build: .
    image: node:15
    ports: 
      - 3000:3000
    restart: always
    environment:
      DB_HOST: db #docker auto pass db container ip
      DB_NAME: ${DB_NAME}
      USER_DB: ${USER_DB}
      PASS_DB: ${PASS_DB}
  adminer:
    image: adminer:latest
    ports: 
      - 8080:8080
    environment: 
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev

volumes: 
  mysql-data:
    driver: local



  

   