# Define .env file as in .env.example 
# than source it before launching compose
version: "3.9"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      #db creation only first run (if volumes attached)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASS_DB}
      MYSQL_DATABASE: ${DB_NAME}
    volumes: 
      - /mnt/meteoserver-sql-data:/var/lib/mysql

  app:
    image: docker.pkg.github.com/matteoformentin/meteoserver/meteoserver:latest
    ports: 
      - 3000:3000
    environment:
      DB_HOST: db #docker auto pass db container ip
      DB_NAME: ${DB_NAME}
      USER_DB: ${USER_DB}
      PASS_DB: ${PASS_DB}
      NODE_ENV: Production

  adminer:
    image: adminer:latest
    ports: 
      - 8080:8080
    environment: 
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev
    
networks:
  main:
    driver: overlay
    attachable: true
